
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS item_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     description VARCHAR (1000) NOT NULL,
     created TIMESTAMP,
     requestor_id BIGINT,
     CONSTRAINT pk_item_request PRIMARY KEY (id),
     CONSTRAINT fk_item_request_to_users FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     name VARCHAR(255) NOT NULL,
     description VARCHAR(1000) NOT NULL,
     available BOOLEAN NOT NULL,
     owner_id BIGINT,
     request_id BIGINT,
     CONSTRAINT pk_item PRIMARY KEY (id),
     CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(id),
     CONSTRAINT fk_items_to_item_request FOREIGN KEY(request_id) REFERENCES item_request(id)
);
