services:
  db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - shareit-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ../server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  gateway:
    build:
      context: ../gateway
    depends_on:
      - server
    ports:
      - "8080:8080"

volumes:
  shareit-db-data: